In [2]:
import numpy as np

# Create a simple 3x3 matrix
A = np.array([[10, 21, 36], [47, 51, 64], [72, 87, 91]])

# Get eigenvalues and eigenvectors
values, vectors = np.linalg.eig(A)

In [3]:
values

array([170.53270055, -12.64773681,  -5.88496373])

In [4]:
vectors

array([[-0.2509516 , -0.87850736,  0.71894055],
       [-0.53175418,  0.22492691, -0.68983358],
       [-0.80886388,  0.42146495,  0.08517112]])

In [5]:

# Diagonalize the eigenvalues
values_diag = np.diag(values)

# Invert the eigenvectors
vectors_inv = np.linalg.inv(vectors)

# Reconstruct the original matrix
A_reconstructed = vectors @ values_diag @ vectors_inv

print(A_reconstructed)


[[10. 21. 36.]
 [47. 51. 64.]
 [72. 87. 91.]]


In [8]:
import numpy as np

def shifting_redirection(M, eigenvalue, eigenvector):
    """
    Apply shifting redirection to the matrix to compute next eigenpair: M = M-lambda v
    """
    return(M-eigenvalue*np.matmul(eigenvector.T, eigenvector))

def power_method(M, epsilon=0.0001, max_iter=10000, iteration=None):
    """
    This function computes the principal component of M by using the power method with parameters:
    - epsilon: (float) Termination criterion to stop the power method when changes in the solution is marginal
    - max_iter: (int) Hard termination criterion
    - iteration: (optional) An integer to indicate the current iteration for logging purposes (if needed)
    Notes:
    - I added another condition based on the dot product of two consecutive solutions
    """
    # Initialization
    x = [None]*int(max_iter)
    x[0] = np.random.rand(M.shape[0])
    x[1] = np.matmul(M, x[0])
    count = 0
    
    # Compute eigenvector
    while((np.linalg.norm(x[count] - x[count-1]) > epsilon) and (count < max_iter)):
        # Actual computations
        x[count+1] = np.matmul(M, x[count]) / np.linalg.norm(np.matmul(M, x[count]))
        count += 1
        
    # Compute eigenvalue
    eigenvalue = np.matmul(np.matmul(x[count].T, M), x[count])
    
    return (x[count], eigenvalue)


def eigenpairs(M, epsilon = 0.00001, max_iter = 10e2, plot = True):
    # Initialization
    eigenvectors = [None]*M.shape[0]
    eigenvalues = [None]*M.shape[0]
    
    for i in range(0, M.shape[0]):
        # Actual computing
        eigenvectors[i], eigenvalues[i] = power_method(M, epsilon, max_iter, iteration = i+1) 
        M = shifting_redirection(M, eigenvalues[i], eigenvectors[i])

    return(eigenvectors, eigenvalues)

In [9]:
# Example matrix
M = np.array([[4, 1], 
              [2, 3]])

# Compute eigenpairs
eigenvectors, eigenvalues = eigenpairs(M)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)


TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

In [10]:
import numpy as np
np.set_printoptions(suppress=True)
import matplotlib.pyplot as plt

In [11]:
A = np.random.randn(3,3)
print(A)

[[ 0.71312284  0.18564539 -0.41922938]
 [-1.75060237  0.67694226 -0.61706012]
 [-2.0085846   0.45285996  0.67457936]]


In [12]:
w, v = np.linalg.eig(A)    # find eigenvalues and eigenvectors
print(f'eigenvalues = {w}')    # each entry is an eigenvalue
print(f'eigenvectors = \n{v}')    # each column is the corresponding eigenvector

eigenvalues = [1.61460984+0.j         0.22501731+0.63683946j 0.22501731-0.63683946j]
eigenvectors = 
[[ 0.39415293+0.j          0.1271097 -0.17202186j  0.1271097 +0.17202186j]
 [-0.13791782+0.j          0.85402423+0.j          0.85402423-0.j        ]
 [-0.90863752+0.j          0.26486287-0.39337245j  0.26486287+0.39337245j]]


In [13]:
D = np.diag(w)    # convert a vector to a diagonal matrix
R = v
A_decomp = np.dot(R, np.dot(D, np.linalg.inv(R)))    # decompose A into eigenmodes
print(A_decomp)

[[ 0.71312284-0.j  0.18564539+0.j -0.41922938+0.j]
 [-1.75060237-0.j  0.67694226+0.j -0.61706012-0.j]
 [-2.0085846 -0.j  0.45285996-0.j  0.67457936-0.j]]


In [15]:
As = (A + A.T) / 2    # construct a real symmetric matrix
print(As)

[[ 0.71312284 -0.78247849 -1.21390699]
 [-0.78247849  0.67694226 -0.08210008]
 [-1.21390699 -0.08210008  0.67457936]]


In [16]:
w, v = np.linalg.eigh(As)    # find eigenvalues and eigenvectors of a Hermitian matrix
print(f'eigenvalues = {w}')    # eigenvalues in ascending order
print(f'eigenvectors = \n{v}')    # each column is the corresponding eigenvector

eigenvalues = [-0.78889466  0.7510029   2.10253622]
eigenvectors = 
[[ 0.69302619 -0.02278465  0.72055226]
 [ 0.40340834  0.8406188  -0.36141631]
 [ 0.59747503 -0.54114776 -0.59176236]]


In [17]:
D = np.diag(w)
R = v
A_decomp = np.dot(R, np.dot(D, R.T))
print(A_decomp)

[[ 0.71312284 -0.78247849 -1.21390699]
 [-0.78247849  0.67694226 -0.08210008]
 [-1.21390699 -0.08210008  0.67457936]]
