In [1]:
import cv2

In [4]:
img = cv2.imread('1.jpg')
# Display the image in a window titled 'First Image'
cv2.imshow('First Image', img)

# Wait for 2 seconds
cv2.waitKey(2000)  # wait for 2000 milliseconds
# cv2.waitKey(0)     # wait forever until key press 

# Close the specific window with title 'First Image'
# cv2.destroyWindow('First Image')
# Close all OpenCV windows that are currently open
cv2.destroyAllWindows()

In [ ]:
# img = cv2.imread('2.jpg')
img = cv2.imread('4.jpg')  # corrected extension
if img is not None:
	cv2.imshow('First Image', img)
	cv2.imshow('Second Image', img)
	cv2.waitKey(0)
	cv2.destroyAllWindows()
else:
	print("Error")

In [11]:
import numpy as np
import cv2

In [13]:
img=cv2.imread('mrunal.png')
cv2.imshow('Actress', img)
cv2.imshow('Actress', img)
cv2.waitKey(0)
cv2.destroyWindow('Actress')

In [15]:
# How to resize the image 
img=cv2.imread('mrunal.png')
resize_img=cv2.resize(img, (300, 500))
cv2.imshow('Actress', img)
cv2.waitKey(0)
cv2.destroyWindow('Actress')

In [20]:
v = np.array([[1,2,3,1,2,3], [1,2,3,1,2,3]])
v

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [21]:
img=cv2.imread('mrunal.png')
print(img)

[[[110 104 116]
  [110 104 116]
  [110 104 116]
  ...
  [120 116 116]
  [126 120 118]
  [129 124 120]]

 [[110 104 116]
  [110 104 116]
  [110 104 116]
  ...
  [120 116 116]
  [126 120 118]
  [129 124 120]]

 [[110 104 116]
  [110 104 116]
  [110 104 116]
  ...
  [119 114 115]
  [126 120 118]
  [129 124 120]]

 ...

 [[ 82  70  72]
  [ 82  70  72]
  [ 85  73  75]
  ...
  [ 66  61  62]
  [ 66  61  62]
  [ 66  61  62]]

 [[ 83  71  73]
  [ 83  71  73]
  [ 85  73  75]
  ...
  [ 69  64  65]
  [ 69  64  65]
  [ 69  64  65]]

 [[ 83  71  73]
  [ 83  71  73]
  [ 85  73  75]
  ...
  [ 70  66  66]
  [ 70  66  66]
  [ 70  66  66]]]


In [19]:
img.shape

(1000, 800, 3)

In [ ]:
# Resize image to 300x500 pixels and save it
resized = cv2.resize(img, (300, 500))
cv2.imwrite('resized_mrunal.png', resized)

In [ ]:
img_sai = cv2.imread('sai.png')
if img_sai is not None:
    resized_sai = cv2.resize(img_sai, (300, 500))
    cv2.imshow('Original Sai', img_sai)
    cv2.imshow('Resized Sai', resized_sai)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
else:
    print("Error: Could not load sai.png")


In [25]:
v = np.array([1,2,3,1,2,3])
np.hstack((v,v))

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [26]:
img_sai = cv2.imread('sai.png')
resized_sai = cv2.resize(img_sai, (300, 500))
horizontal_ = np.hstack((resized_sai, resized_sai))
cv2.imshow('Resized Sai', horizontal_)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [27]:
img_sai = cv2.imread('sai.png')
resized_sai = cv2.resize(img_sai, (300, 500))
vertical_ = np.vstack((resized_sai, resized_sai))
cv2.imshow('Resized Sai', vertical_)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [32]:
img_sai = cv2.imread('sai.png')
resized_sai = cv2.resize(img_sai, (300, 500))
horizontal_ = np.hstack((resized_sai, resized_sai, resized_sai))
vertical_ = np.vstack((horizontal_, horizontal_))
cv2.imshow('Resized Sai', vertical_)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
img_sai = cv2.imread('sai.png')
resized_sai = cv2.resize(img_sai, (300, 500))
horizontal_ = np.hstack((resized_sai, resized_sai, resized_sai))
vertical_ = np.vstack((horizontal_, horizontal_))
cv2.imshow('Resized Sai', vertical_)
cv2.waitKey(0)
cv2.destroyAllWindows()

#### **Slide `show()`**

In [39]:
import os
name_list=os.listdir("D:\\DEEP LEARNING\\Computer Vision\\wscube")

In [40]:
name_list

['01.introduction.ipynb',
 'allu.png',
 'jaspreet.png',
 'mrunal.png',
 'ram.png',
 'rohit.png',
 'sai.png',
 'sharma.png']

In [43]:
for name in name_list:
    path="D:\\DEEP LEARNING\\Computer Vision\\wscube"
    img_name=path+"\\"+name
    img=cv2.imread(img_name)
    if img is not None:
        resized_img = cv2.resize(img, (500, 700))
        cv2.imshow('Test Imgs', resized_img)
        cv2.waitKey(2000)
        cv2.destroyAllWindows()
    else:
        print(f"Could not read image: {name}")

Could not read image: 01.introduction.ipynb


In [44]:
for name in name_list:
    path="D:\\DEEP LEARNING\\Computer Vision\\wscube"
    img_name=path+"\\"+name
    img=cv2.imread(img_name)
    if img is not None:
        resized_img = cv2.resize(img, (500, 700))
        cv2.imshow('Test Imgs', resized_img)
        cv2.waitKey(0)
        cv2.destroyAllWindows()
    else:
        print(f"Could not read image: {name}")

Could not read image: 01.introduction.ipynb


In [46]:
# import cv2 
img=cv2.imread('jaspreet.png')
# print(img)
print(img.shape)
img=cv2.resize(img, (500, 500))
cv2.imshow("Jaspreet", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

(375, 500, 3)


- **cv2.IMREAD_COLOR**: It specifies to load a color image. Any transparency of the image will be neglected. It is the default flag. Alternatively, we can pass integer value **1** for this flag.  

- **cv2.IMREAD_GRAYSCALE**: It specifies to load an image in grayscale mode. Alternatively, we can pass integer value **0** for this flag.  

- **cv2.IMREAD_UNCHANGED**: It specifies to load an image as is, including the alpha channel. Alternatively, we can pass integer value **-1** for this flag.

In [47]:
# import cv2 
img=cv2.imread('jaspreet.png', 1)
print(img.shape)
img=cv2.resize(img, (500, 500))
cv2.imshow("Jaspreet", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

(375, 500, 3)


In [51]:
img = cv2.imread('allu.png', 0)  # BGR  (0-255)
if img is not None:
	print(img.shape)
	img = cv2.resize(img, (500, 500))
	cv2.imshow("allu", img)
	cv2.waitKey(0)
	cv2.destroyAllWindows()
else:
	print("Error: Could not load virat.png")

(889, 500)


In [52]:
# import cv2 
img=cv2.imread('ram.png', -1)
print(img.shape)
img=cv2.resize(img, (500, 500))
cv2.imshow("ram", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

(500, 500, 3)


In [53]:
## useful for Deep Learning
import cv2

img = cv2.imread('allu.png')  # Default is BGR
if img is not None:
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)  # Convert to RGB
    print("BGR to RGB Conversion Done")
    cv2.imshow("RGB Image", img_rgb)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
else:
    print("Error: Could not load allu.png")


BGR to RGB Conversion Done


In [54]:
import cv2

img = cv2.imread('rohit.png')  # Load in BGR format
if img is not None:
    b, g, r = cv2.split(img)  # Extract individual color channels
    merged = cv2.merge([b, g, r])  # Merge them back
    print("Channels Split and Merged Successfully")
    cv2.imshow("Merged Image", merged)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
else:
    print("Error: Could not load allu.png")


Channels Split and Merged Successfully


### Parameters for cv2.putText()

#### org  
- Defines text position using (x,y) coordinates
- x: Distance from left edge
- y: Distance from top edge
- Example: (50,100) places text 50 pixels from left, 100 pixels from top

#### fontFace  
Different font styles provided by OpenCV:
- FONT_HERSHEY_SIMPLEX (0): Normal size sans-serif
- FONT_HERSHEY_PLAIN (1): Small size sans-serif  
- FONT_HERSHEY_DUPLEX (2): More complex sans-serif
- FONT_HERSHEY_COMPLEX (3): More complex serif
- FONT_HERSHEY_TRIPLEX (4): More complex serif with thicker strokes
- FONT_HERSHEY_COMPLEX_SMALL (5): Smaller version of complex
- FONT_HERSHEY_SCRIPT_SIMPLEX (6): Hand-writing style
- FONT_HERSHEY_SCRIPT_COMPLEX (7): More complex hand-writing style

#### color  
- Uses BGR color format (Blue, Green, Red)
- Values range from 0-255 for each channel
- Example: (255,0,0) is pure blue

#### lineType  
Controls how lines/text edges are rendered:
- FILLED (-1): Fills entire text
- LINE_4 (4): 4-connected line
- LINE_8 (8): 8-connected line (default)
- LINE_AA (16): Anti-aliased line

#### bottomLeftOrigin 
- Controls text origin point
- False (default): Origin at top-left
- True: Origin at bottom-left

#### **Image**

In [64]:
img_get = cv2.imread('mrunal1.png') 
img_get = cv2.resize(img_get, (500, 500))
img = img_get
text = "Mrunal"
org = (50, 100)
fontFace = cv2.FONT_HERSHEY_DUPLEX
fontScale = 3
color = (0, 0, 255)  # BGR color format
thickness = 3
lineType = cv2.LINE_8
bottomLeftOrigin = False

cv2.putText(img, text, org, fontFace, fontScale, color, thickness, lineType, bottomLeftOrigin)


cv2.imshow("Mrunal", img_get)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [66]:
text = "Mrunal"
org1 = (50, 100)  # First text position
org2 = (50, 200)  # Second text position, increased y-coordinate to place it below

# First text
cv2.putText(img, text, org1, fontFace, fontScale, color, thickness, lineType, bottomLeftOrigin)
# Second text
cv2.putText(img, text, org2, fontFace, fontScale, color, thickness, lineType, bottomLeftOrigin)

cv2.imshow("Mrunal", img)
cv2.waitKey(0)
cv2.destroyAllWindows()


### Bounding Boxex

**Line on image**

In [74]:
img=cv2.imread('sai.png')
img=cv2.resize(img, (300, 500))
# Add line
new_img=cv2.line(img=img, pt1=(130, 40), pt2=(200, 40), color=(0,255,0), thickness=2, lineType=4)
cv2.imshow("Sai", new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()



**Rectangle**

In [77]:
img=cv2.imread('sai.png')
img=cv2.resize(img, (300, 500))
# Add line
new_img=cv2.rectangle(img=img, pt1=(130, 35), pt2=(200, 120), color=(0,255,0), thickness=2, lineType=4)
cv2.imshow("Sai", new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()



text with rectangle

In [87]:
img=cv2.imread('sai.png')
img=cv2.resize(img, (300, 500))
# Add rectangle
new_img=cv2.rectangle(img=img, pt1=(130, 35), pt2=(200, 120), color=(0,255,0), thickness=2, lineType=4)
# Add text inside rectangle
text = "SAI"
cv2.putText(new_img, text, (150, 140), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0,255,0), 2, lineType)
cv2.imshow("Sai", new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()


#### Circle on image

In [ ]:
import cv2
img=cv2.imread('mrunal.png')
img=cv2.resize(img, (500, 700))
center_coordinates = (220, 150) 
radius = 80
color = (0,255,0) 
thickness = 4
# thickness = -1
image = cv2.circle(img, center_coordinates, radius, color, thickness)
cv2.imshow("Mrunal", image) 
cv2.waitKey(0)
cv2.destroyAllWindows()


### ellipse

In [12]:

import cv2
img=cv2.imread('sai.png')
img=cv2.resize(img, (500, 700))
image = cv2.ellipse(img=img, center=(270, 130), axes=(60, 50), angle=60, startAngle=0, endAngle=360, color=(0, 255, 0), thickness=4, lineType=16)
cv2.imshow("Sai", image) 
cv2.waitKey(0)
cv2.destroyAllWindows()


In [13]:
import numpy as np   
Img = np.zeros((512, 512, 3), np.uint8)   
window_name = 'Image'  
center_coordinates = (220, 150)  
radius, color, thickness = 100, (255, 133, 233), -1  

image = cv2.circle(Img, center_coordinates, radius, color, thickness)   
cv2.imshow(window_name, image)   
cv2.waitKey(0)   
cv2.destroyAllWindows()