In [1]:
# %pip install opencv-python
import cv2

In [4]:
img = cv2.imread('mrunal.png')  # Changed extension from jpg to png
if img is not None:
    # Display the image in a window titled 'First Image'
    cv2.imshow('First Image', img)
    
    # Wait for 2 seconds
    cv2.waitKey(2000)  # wait for 2000 milliseconds
    
    # Close all OpenCV windows
    cv2.destroyAllWindows()
else:
    print("Error: Could not load the image")

In [5]:
# img = cv2.imread('2.jpg')
img = cv2.imread('4.jpg')  # corrected extension
if img is not None:
	cv2.imshow('First Image', img)
	cv2.imshow('Second Image', img)
	cv2.waitKey(0)
	cv2.destroyAllWindows()
else:
	print("Error")

Error


In [1]:
import numpy as np
import cv2

In [ ]:
img=cv2.imread('mrunal.png')
cv2.imshow('Actress', img)
# cv2.imshow('Actress', img)
cv2.waitKey(0)
cv2.destroyWindow('Actress')

In [10]:
# How to resize the image 
img=cv2.imread('mrunal.png')
# resize_img=cv2.resize(img, (300, 500))
resize_img=cv2.resize(img, (400, 500))
cv2.imshow('Actress', resize_img)
cv2.waitKey(0)
cv2.destroyWindow('Actress')

In [11]:
v = np.array([[1,2,3,1,2,3], [1,2,3,1,2,3]])
v

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [12]:
img=cv2.imread('mrunal.png')
print(img)

[[[110 104 116]
  [110 104 116]
  [110 104 116]
  ...
  [120 116 116]
  [126 120 118]
  [129 124 120]]

 [[110 104 116]
  [110 104 116]
  [110 104 116]
  ...
  [120 116 116]
  [126 120 118]
  [129 124 120]]

 [[110 104 116]
  [110 104 116]
  [110 104 116]
  ...
  [119 114 115]
  [126 120 118]
  [129 124 120]]

 ...

 [[ 82  70  72]
  [ 82  70  72]
  [ 85  73  75]
  ...
  [ 66  61  62]
  [ 66  61  62]
  [ 66  61  62]]

 [[ 83  71  73]
  [ 83  71  73]
  [ 85  73  75]
  ...
  [ 69  64  65]
  [ 69  64  65]
  [ 69  64  65]]

 [[ 83  71  73]
  [ 83  71  73]
  [ 85  73  75]
  ...
  [ 70  66  66]
  [ 70  66  66]
  [ 70  66  66]]]


In [13]:
img.shape

(1000, 800, 3)

In [14]:
# Resize image to 300x500 pixels and save it
resized = cv2.resize(img, (300, 500))
cv2.imwrite('resized_mrunal.png', resized)

True

In [15]:
img_sai = cv2.imread('sai.png')
if img_sai is not None:
    resized_sai = cv2.resize(img_sai, (300, 500))
    cv2.imshow('Original Sai', img_sai)
    cv2.imshow('Resized Sai', resized_sai)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
else:
    print("Error: Could not load sai.png")


In [25]:
v = np.array([1,2,3,1,2,3])
np.hstack((v,v))

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [16]:
img_sai = cv2.imread('sai.png')
resized_sai = cv2.resize(img_sai, (300, 500))
horizontal_ = np.hstack((resized_sai, resized_sai))
cv2.imshow('Resized Sai', horizontal_)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [27]:
img_sai = cv2.imread('sai.png')
resized_sai = cv2.resize(img_sai, (300, 500))
vertical_ = np.vstack((resized_sai, resized_sai))
cv2.imshow('Resized Sai', vertical_)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [17]:
img_sai = cv2.imread('sai.png')
resized_sai = cv2.resize(img_sai, (300, 500))
horizontal_ = np.hstack((resized_sai, resized_sai, resized_sai))
vertical_ = np.vstack((horizontal_, horizontal_))
cv2.imshow('Resized Sai', vertical_)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [18]:
img_sai = cv2.imread('sai.png')
resized_sai = cv2.resize(img_sai, (300, 500))
horizontal_ = np.hstack((resized_sai, resized_sai, resized_sai))
vertical_ = np.vstack((horizontal_, horizontal_))
cv2.imshow('Resized Sai', vertical_)
cv2.waitKey(0)
cv2.destroyAllWindows()

#### **Slide `show()`**

In [19]:
import os
name_list=os.listdir("D:\\DEEP LEARNING\\Computer Vision\\wscube")

In [20]:
name_list

['01.introduction.ipynb',
 '02-Video.ipynb',
 'jaspreet.png',
 'mrunal.png',
 'mrunal1.png',
 'ram.png',
 'resized_mrunal.png',
 'rohit.png',
 'sai.png',
 'sai1.png',
 'sharma.png']

In [22]:
for name in name_list:
    path="D:\\DEEP LEARNING\\Computer Vision\\wscube"
    img_name=path+"\\"+name
    img=cv2.imread(img_name)
    if img is not None:
        resized_img = cv2.resize(img, (500, 700))
        cv2.imshow('Test Imgs', resized_img)
        cv2.waitKey(2000)
        cv2.destroyAllWindows()
    else:
        print(f"Could not read image: {name}")

Could not read image: 01.introduction.ipynb
Could not read image: 02-Video.ipynb


In [23]:
for name in name_list:
    path="D:\\DEEP LEARNING\\Computer Vision\\wscube"
    img_name=path+"\\"+name
    img=cv2.imread(img_name)
    if img is not None:
        resized_img = cv2.resize(img, (500, 700))
        cv2.imshow('Test Imgs', resized_img)
        cv2.waitKey(0)
        cv2.destroyAllWindows()
    else:
        print(f"Could not read image: {name}")

Could not read image: 01.introduction.ipynb
Could not read image: 02-Video.ipynb


In [24]:
# import cv2 
img=cv2.imread('jaspreet.png')
# print(img)
print(img.shape)
img=cv2.resize(img, (500, 500))
cv2.imshow("Jaspreet", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

(375, 500, 3)


### **Image Reading Flags in OpenCV**

- **1 or `cv2.IMREAD_COLOR`**: Loads color image (default)
- **0 or `cv2.IMREAD_GRAYSCALE`**: Loads image in grayscale
- **-1 or `cv2.IMREAD_UNCHANGED`**: Loads image as-is with alpha channel

In [47]:
# import cv2 
img=cv2.imread('jaspreet.png', 1)
print(img.shape)
img=cv2.resize(img, (500, 500))
cv2.imshow("Jaspreet", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

(375, 500, 3)


In [29]:
img = cv2.imread('roko.jpg', 0)  # BGR  (0-255)
img = cv2.imread('roko.jpg', -1)  # BGR  (0-255)
img = cv2.imread('roko.jpg', 1)  # BGR  (0-255)
if img is not None:
	print(img.shape)
	img = cv2.resize(img, (500, 500))
	cv2.imshow("allu", img)
	cv2.waitKey(0)
	cv2.destroyAllWindows()
else:
	print("Error: Could not load allu.png")

(1080, 1080, 3)


In [31]:
# import cv2 
img=cv2.imread('ram.png', -1)
print(img.shape)
img=cv2.resize(img, (500, 500))
cv2.imshow("ram", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

(500, 500, 3)


In [53]:
## useful for Deep Learning
import cv2

img = cv2.imread('allu.png')  # Default is BGR
if img is not None:
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)  # Convert to RGB
    print("BGR to RGB Conversion Done")
    cv2.imshow("RGB Image", img_rgb)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
else:
    print("Error: Could not load allu.png")


BGR to RGB Conversion Done


In [ ]:
import cv2

img = cv2.imread('rohit.png')  # Load in BGR format
if img is not None:
    b, g, r = cv2.split(img)  # Extract individual color channels
    merged = cv2.merge([b, g, r])  # Merge them back
    print("Channels Split and Merged Successfully")
    cv2.imshow("Merged Image", merged)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
else:
    print("Error: Could not load rohit.png")


Channels Split and Merged Successfully


### **Parameters for `cv2.putText()`**

#### **Text Position (`org`)**
- Uses (x,y) coordinates
- Example: (50,100) means:
    - 50 pixels from left
    - 100 pixels from top

#### **Font Style (`fontFace`)**
- `FONT_HERSHEY_SIMPLEX`: Basic font
- `FONT_HERSHEY_PLAIN`: Simple thin font  
- `FONT_HERSHEY_DUPLEX`: Thicker font
- `FONT_HERSHEY_COMPLEX`: More stylized font
- And more...

#### **Color**
- Uses (Blue, Green, Red) values 
- Each color ranges 0-255
- Example: `(255,0,0)` is bright blue

#### **Line Style (`lineType`)**
- `FILLED (-1)`: Solid filled text
- `LINE_4 (4)`: Basic lines
- `LINE_8 (8)`: Smoother lines
- `LINE_AA (16)`: Smoothest lines

#### **Origin Point (`bottomLeftOrigin`)**
- `False`: Start from top-left (default)
- `True`: Start from bottom-left


#### **Image**

In [35]:
# Create a blank image
img = np.zeros((500, 800, 3), dtype=np.uint8)

# Add text to the image
cv2.putText(img, "Hello OpenCV!", (50, 200), cv2.FONT_HERSHEY_SIMPLEX, 
            2, (255, 0, 0), 3, cv2.LINE_AA)

# Display the image
cv2.imshow("Image with Text", img)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [36]:
import cv2
import numpy as np

# Create a blank white image
image = np.ones((400, 600, 3), dtype=np.uint8) * 255

# Define the text and its properties
text = "OpenCV Example"
org = (50, 200)  # Bottom-left corner of the text
fontFace = cv2.FONT_HERSHEY_SIMPLEX
fontScale = 1.5
color = (0, 0, 255)  # Red color in BGR
thickness = 2
lineType = cv2.LINE_AA

# Add text to the image
cv2.putText(image, text, org, fontFace, fontScale, color, thickness, lineType)

# Display the image
cv2.imshow('Image with Text', image)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [39]:
img_get = cv2.imread('mrunal1.png') 
img_get = cv2.resize(img_get, (500, 500))

img = img_get # Copy the resized image to work with
text = "Mrunal" # Text to be displayed on the image
org = (50, 100) # Position coordinates (x=50, y=100 from top-left)
fontFace = cv2.FONT_HERSHEY_DUPLEX  # Font style - thicker than SIMPLEX
fontScale = 3 # Size of the text (larger number = bigger text)
color = (0, 0, 255) # BGR color format - Red color (0 Blue, 0 Green, 255 Red)
thickness = 3 # Thickness of the text lines
lineType = cv2.LINE_8 # Line type for smoother text edges
bottomLeftOrigin = False # If True, origin point starts from bottom-left; False means top-left

cv2.putText(img, text, org, fontFace, fontScale, color, thickness, lineType, bottomLeftOrigin)


cv2.imshow("Mrunal", img_get)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [40]:
text = "Mrunal"
org1 = (50, 100)  # First text position
org2 = (50, 200)  # Second text position, increased y-coordinate to place it below

# First text
cv2.putText(img, text, org1, fontFace, fontScale, color, thickness, lineType, bottomLeftOrigin)
# Second text
cv2.putText(img, text, org2, fontFace, fontScale, color, thickness, lineType, bottomLeftOrigin)

cv2.imshow("Mrunal", img)
cv2.waitKey(0)
cv2.destroyAllWindows()


### **Bounding Boxes**
- Used to highlight or mark regions of interest in images
- Common drawing functions:
    - `cv2.rectangle()`: Draw rectangular boxes
    - `cv2.circle()`: Draw circular boundaries 
    - `cv2.line()`: Draw line segments
    - `cv2.ellipse()`: Draw elliptical shapes
- Key parameters:
    - Image matrix
    - Start coordinates (x1,y1)
    - End coordinates (x2,y2) 
    - Color in BGR format
    - Thickness (-1 for filled shape)
    - Line type (4/8/16)

**Line on image**

In [42]:
img=cv2.imread('sai.png')
img=cv2.resize(img, (300, 500))
# Add line
new_img=cv2.line(img=img, pt1=(130, 40), pt2=(200, 40), color=(0,255,0), thickness=2, lineType=4)
cv2.imshow("Sai", new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()



In [ ]:
import cv2

# Load and resize the image
img = cv2.imread('sai.png')
if img is not None:
    img = cv2.resize(img, (300, 500))

    # Draw a green line
    cv2.line(img, pt1=(50, 50), pt2=(250, 50), color=(0, 255, 0), thickness=2, lineType=cv2.LINE_8)

    # Display the image with shapes
    cv2.imshow("Bounding Box Example", img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
else:
    print("Error: Could not load sai.png")


**Rectangle**

In [44]:
img=cv2.imread('sai.png')
img=cv2.resize(img, (300, 500))
# Add line
new_img=cv2.rectangle(img=img, pt1=(130, 35), pt2=(200, 120), color=(0,255,0), thickness=2, lineType=4)
cv2.imshow("Sai", new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()



text with rectangle

In [87]:
img=cv2.imread('sai.png')
img=cv2.resize(img, (300, 500))
# Add rectangle
new_img=cv2.rectangle(img=img, pt1=(130, 35), pt2=(200, 120), color=(0,255,0), thickness=2, lineType=4)
# Add text inside rectangle
text = "SAI"
cv2.putText(new_img, text, (150, 140), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0,255,0), 2, lineType)
cv2.imshow("Sai", new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()


#### Circle on image

In [ ]:
import cv2
img=cv2.imread('mrunal.png')
img=cv2.resize(img, (500, 700))
center_coordinates = (220, 150) 
radius = 80
color = (0,255,0) 
thickness = 4
# thickness = -1
image = cv2.circle(img, center_coordinates, radius, color, thickness)
cv2.imshow("Mrunal", image) 
cv2.waitKey(0)
cv2.destroyAllWindows()


### ellipse

In [12]:

import cv2
img=cv2.imread('sai.png')
img=cv2.resize(img, (500, 700))
image = cv2.ellipse(img=img, center=(270, 130), axes=(60, 50), angle=60, startAngle=0, endAngle=360, color=(0, 255, 0), thickness=4, lineType=16)
cv2.imshow("Sai", image) 
cv2.waitKey(0)
cv2.destroyAllWindows()


In [13]:
import numpy as np   
Img = np.zeros((512, 512, 3), np.uint8)   
window_name = 'Image'  
center_coordinates = (220, 150)  
radius, color, thickness = 100, (255, 133, 233), -1  

image = cv2.circle(Img, center_coordinates, radius, color, thickness)   
cv2.imshow(window_name, image)   
cv2.waitKey(0)   
cv2.destroyAllWindows()

In [46]:
import cv2

# Load and resize the image
img = cv2.imread('flowers.jpg')
if img is not None:
    img = cv2.resize(img, (300, 500))

    # Draw a green line
    cv2.line(img, (50, 50), (250, 50), (0, 255, 0), thickness=2, lineType=cv2.LINE_8)

    # Draw a red rectangle
    cv2.rectangle(img, (50, 100), (250, 300), (0, 0, 255), thickness=3)

    # Draw a blue circle
    cv2.circle(img, (150, 400), 40, (255, 0, 0), thickness=-1)

    # Draw a yellow ellipse
    cv2.ellipse(img, (150, 200), (80, 50), 0, 0, 180, (255, 255, 0), thickness=2)

    # Display the image with shapes
    cv2.imshow("Bounding Box Example", img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
else:
    print("Error: Could not load sai.png")
