In [3]:
import numpy as np
np.__version__

'2.0.2'

In [6]:
arr=np.array([1,2,3])

In [7]:
arr

array([1, 2, 3])

In [8]:
arr_v=np.array([[1], [2], [3]])

In [9]:
arr_v

array([[1],
       [2],
       [3]])

In [10]:
arr2=np.array([(1,2,3), (4,5,6)])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr3=np.array([[(1,2,3), (4,5,6)],[(1,2,3), (4,5,6)],[(1,2,3), (4,5,6)]])
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [14]:
np.zeros((3,3), dtype="uint")

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=uint64)

In [15]:
np.ones((3,4), dtype="uint")

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=uint64)

In [17]:
np.full((3,4),5, dtype="uint")

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]], dtype=uint64)

In [20]:
np.eye((3),dtype="uint")

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=uint64)

In [29]:
a=np.arange(0,13,1)

In [30]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [33]:
# Option 1: Using the first 12 elements to create a 3x4 matrix
a[:-1].reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
np.random.rand(2,3)*255

array([[202.21749341,  97.6779899 , 202.84865091],
       [199.94078428, 242.1646092 , 142.29299779]])

In [35]:
arr=np.array([(1,2,3),(2,2,3)])

In [36]:
arr

array([[1, 2, 3],
       [2, 2, 3]])

In [37]:
arr.size

6

In [38]:
arr.ndim

2

In [39]:
arr.dtype

dtype('int64')

In [40]:
arr1=arr.astype(float)

In [41]:
arr1.dtype

dtype('float64')

In [42]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [43]:
arr.min()

np.int64(1)

In [44]:
arr.max()

np.int64(3)

In [45]:
arr=np.array([(1,2,3,4),(14,5,6,7)])

In [46]:
print(arr)

[[ 1  2  3  4]
 [14  5  6  7]]


In [47]:
arr[0,1:]

array([2, 3, 4])

In [48]:
arr[1,1:]

array([5, 6, 7])

In [50]:
arr[0,1:3]

array([2, 3])

In [51]:
arr[::-1]

array([[14,  5,  6,  7],
       [ 1,  2,  3,  4]])

In [52]:
arr.reshape(1,8)

array([[ 1,  2,  3,  4, 14,  5,  6,  7]])

In [53]:
arr1=np.arange(10)

In [54]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
arr1=np.append(arr1, 566)

In [56]:
arr1

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9, 566])

In [ ]:
a=np.arange(9).reshape(3,3)
b=np.arange(9).reshape(3,3)

In [60]:
c=np.ravel(a)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
c=np.ravel(a)
c

In [61]:
arrr4=arr.copy()

In [62]:
arrr4

array([[ 1,  2,  3,  4],
       [14,  5,  6,  7]])

In [10]:
import numpy as np

In [11]:
# image creation
img=np.zeros((500,500))
img[:,:]=100

In [12]:
img=img[:,:]*10

In [13]:
img[100:100, 200:300]=255

In [14]:
# %pip install opencv-python


In [15]:
import cv2
print(cv2.__version__)

4.11.0


In [17]:
cv2.imwrite('sample.jpg', img)

True

True

In [20]:
import sys
print(len(sys.argv))
print(sys.argv[0])
print(sys.argv[1])

2
C:\Users\Admin\AppData\Roaming\Python\Python310\site-packages\ipykernel_launcher.py
--f=c:\Users\Admin\AppData\Roaming\jupyter\runtime\kernel-v3a30cd866538aa1796b9f41bee9a7e702c726eb42.json
